## **Лабороторная работа "Надаль на глине"**

Некоторые считают, что Надаль лучший игрок всех времен на глиняных кортах. Он выиграл 9 чемпионатов Франции, всего одержал 14 побед на турнирах большого шлема (на июнь 2014 года).

Посмотрим, что можно выяснить, анализируя результаты Надаля в 2008-2012 годах.

In [ ]:
# Импортируем необходимые библиотеки
import numpy as np
import pandas as pd
from scipy.stats import norm, chi2_contingency
import statsmodels.api as sm

**Задача:** Верно ли, что результаты Надаля на кортах с глиняным покрытием выше, чем на других
покрытиях?

$H_0$: доля выигранных геймов одинакова для разных покрытий

$H_1$: доля выигранных геймов различается между покрытиями

Уровень значимости: $ \alpha = 0.05 $

In [ ]:
total_table = pd.DataFrame([[1660, 863], [3658, 2715]],
                                 index=['Clay', 'Nonclay'],
                                 columns=['WIN', 'LOSS'])
total_table

          WIN  LOSS
Clay     1660   863
Nonclay  3658  2715

In [ ]:
s1 = 1660
n1 = 2523
s2 = 3658
n2 = 6373

z1, p_value1 = sm.stats.proportions_ztest([s1, s2], [n1, n2])
print(f'z-тест = {z1:.12f}, p_value = {p_value1:.12f}')

z-тест = 7.279826592693, p_value = 0.000000000000

In [ ]:
chi2, p_value, dof, exp = chi2_contingency(total_table, correction=False)
print(f'χ²: {chi2:.12f}, p-value: {p_value:.12f}')

χ²: 52.995875219680, p-value: 0.000000000000

$p-value < 0.05$, гипотеза $H_0$ отвергается.

Разница результатов в зависимости от типа покрытия статистичеки значима.

Надаль выигрывает чаще на глиняном покрытии ($65.8 $%) по сравнению с другими покрытиями ($57.4$%).

Проверим, какие получатся результаты, если учитывать тип гейма (подача и прием подачи).

Результаты Надаля на глиняных и других кортах — геймы, в которых он подавал

In [ ]:
submit_table = pd.DataFrame([[1090, 171], [2747, 446]],
                                 index=['Clay', 'Nonclay'],
                                 columns=['WIN', 'LOSS'])
submit_table

          WIN  LOSS
Clay     1090   171
Nonclay  2747   446

In [ ]:
sub_s1 = 1090
sub_n1 = 1261
sub_s2 = 2747
sub_n2 = 3193

z2, p_value2 = sm.stats.proportions_ztest([sub_s1, sub_s2], [sub_n1, sub_n2])
print(f'z-тест = {z2:.12f}, p_value = {p_value2:.12f}')

z-тест = 0.354570750872, p_value = 0.722911191632

In [ ]:
chi2, p_value, dof, exp = chi2_contingency(submit_table, correction=False)
print(f'χ²: {chi2:.12f}, p-значение: {p_value:.12f}')

χ²: 0.125720417374, p-значение: 0.722911191632

$p-value > 0.05$, гипотеза $H_0$ не отвергается.

Разница результатов в зависимости от типа покрытия не является статистичеки значимой в геймах, когда Надаль подавал ($86.4$% на глиняном покрытии vs $86$% на других покрытиях).

Нет статистических оснований утверждать, что тип покрытия корта влияет на выигрыш Надаля в геймах, когда он подавал.

Результаты Надаля на глиняных и других кортах — геймы, в которых он принимал подачу

In [ ]:
accept_table = pd.DataFrame([[570, 692], [911, 2269]],
                                 index=['Clay', 'Nonclay'],
                                 columns=['WIN', 'LOSS'])
accept_table

         WIN  LOSS
Clay     570   692
Nonclay  911  2269

In [ ]:
acc_s1 = 570
acc_n1 = 1262
acc_s2 = 911
acc_n2 = 3180

z3, p_value3 = sm.stats.proportions_ztest([acc_s1, acc_s2], [acc_n1, acc_n2])
print(f'z-тест = {z3:.12f}, p_value = {p_value3:.12f}')

z-тест = 10.531957990552, p_value = 0.000000000000

In [ ]:
chi2, p_value, dof, exp = chi2_contingency(accept_table, correction=False)
print(f'χ²: {chi2:.12f}, p-значение: {p_value:.12f}')

χ²: 110.922139114746, p-значение: 0.000000000000

$p-value < 0.05$, гипотеза $H_0$ отвергается.

Разница результатов в зависимости от типа покрытия статистичеки значима в геймах, когда Надаль принимал подачу.

Надаль выигрывает чаще на глиняном покрытии ($45.2$% ) чем на других ($28.6$%) в геймах, когда принимает подачу.

**Вывод:** Полученные результаты свидетельствуют о том, что результаты Надаля на кортах с глиняным покрытием выше, чем на других покрытиях, но это может быть связано с типом гейма. В геймах, где Надаль подает, не обнаружено статистичеки значимых различий между типами покрытия корта. При этом в геймах, где Надаль принимает подачу, разница результатов в зависимости от типа покрытия статистичеки значима.